apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    project: task-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    project: task-manager